bitwarden/self-host

- .github/workflows/release.yml
- .github/workflows/update-versions.yml
- bitwarden.ps1
- bitwarden.sh
- run.ps1
- run.sh
This PR adds the initial files to the repository.
> Initial commit

- .github/workflows/release.yml
- .github/workflows/update-versions.yml
This PR updates the `get-release-version` action to the latest version.
> Update 'get-release-version' action to latest version

- .github/workflows/release.yml
This PR fixes referencing the wrong variable during creation of the GitHub Release Draft.
> Fix version variables in GitHub Release Draft

- .github/workflows/update-links.yml
- bitwarden.ps1
- bitwarden.sh
This PR updates the `bitwarden` scripts so that they download using links shortened by Rebrandly.  It also adds an `Update Links` workflow that will run when a release is published to update the destination URLs of the links in Rebrandly.
> Update Scripts and Add Update Links workflow

- .github/workflows/update-links.yml
This PR updates the Rebrandly action to the latest version.
> Update Rebrandly action version

- bitwarden.ps1
- bitwarden.sh
- run.ps1
- run.sh
Merge in latest changes for the self-host scripts from the server repo.
> Update scripts from server repo

- .github/workflows/release.yml
- .github/workflows/update-links.yml
- .github/workflows/update-versions.yml
- bitwarden.sh
Update actions versions. This PR also updates logic on when to create a PR for automated version updating.
> Update workflows with new actions

- .github/workflows/release-digital-ocean.yml
- DigitalOceanMarketplace/files/etc/ufw/applications.d/bitwarden
- DigitalOceanMarketplace/files/etc/update-motd.d/99-bitwarden-welcome
- DigitalOceanMarketplace/files/opt/bitwarden/install-bitwarden.sh
- DigitalOceanMarketplace/files/var/lib/cloud/scripts/per-instance/001_onboot
- DigitalOceanMarketplace/marketplace-image.json
- DigitalOceanMarketplace/scripts/01-setup-first-run.sh
- DigitalOceanMarketplace/scripts/02-ufw-bitwarden.sh
- DigitalOceanMarketplace/scripts/03-force-ssh-logout.sh
- DigitalOceanMarketplace/scripts/90-cleanup.sh
- DigitalOceanMarketplace/scripts/99-img-check.sh
- README.md
Migrates the Digital Ocean contents from [server](https://github.com/bitwarden/server) for easier management.
Additional changes:
- Adds workflow to automatically build and publish the Digital Ocean snapshots when a release is created.
- Adds a workflow step to cleanup image if branch isn't `master`, `rc`, `hotfix`.
- Adds "Deploy to Digital Ocean" button to the README.
> Migrate Digital Ocean 1-click to self hosted repo

- .github/workflows/release.yml
- .gitignore
Add publish stage to push `version.json` file to S3 bucket.
> DEVOPS-772 Build CDN endpoint for selfhost version.json

- README.md
Adds a note on the README to visit the clients project for issues regarding clients.
> Add clients to README

- .github/workflows/release.yml
Add Scim to release matrix to apply lastest tag to it
> Add SCIM to release pipeline to apply latest tag

- .github/workflows/release.yml
Adds tagging for new `web-sh` image during the release.
> Add web-ee image tagging with latest

- .github/workflows/release.yml
Passed act dry-run.
Relates to: https://bitwarden.atlassian.net/browse/CLOUDOPS-189
and
https://bitwarden.atlassian.net/browse/DEVOPS-1019
> [CLOUDOPS-189] S3 to R2 migration

- .github/workflows/release.yml
This PR changes the DCT environment variable to 0 when it is pushing the SCIM image
> change DCT for Scim

- .github/workflows/release.yml
- .github/workflows/update-versions.yml
https://bitwarden.atlassian.net/browse/DEVOPS-951
> Deprecate the rc branching pattern

- .github/workflows/release-digital-ocean.yml
- .github/workflows/release.yml
- .github/workflows/update-links.yml
- changing CI-only SP KV job names
> [DEVOPS-1259] changing CI-only SP KV job names

- .github/workflows/release-digital-ocean.yml
- .github/workflows/release-web-latest.yml
- .github/workflows/release.yml
- .github/workflows/update-links.yml
- .github/workflows/update-versions.yml
- Update all the workflow actions pinned versions
- .github/workflows/*
> [DEVOPS-1392] update all actions pin

- .github/workflows/release-digital-ocean.yml
- DigitalOceanMarketplace/marketplace-image.pkr.hcl
- DigitalOceanMarketplace/scripts/99-img-check.sh
This PR updates the Digital Ocean script for checking the image and also the proper VM size for the Bitwarden stack.
> Update DigitalOcean image files

- .github/workflows/build-unified.yml
This PR updates the `Build Self-Host Unified` workflow to add the `workflow_call` event trigger.  There are also some logic updates to make sure we are using the correct branch name everywhere.
> Update Build Self-Host Unified workflow for workflow_call event

- .github/workflows/build-unified.yml
This PR fixes a minor bug where calling the workflow from another repository did not execute correctly.
> Fix minor input bug in Build Unified workflow

- .github/workflows/release.yml
This PR fixes some syntax errors with the `release-unified` job in the `Release` workflow.
> Fix release workflow for unified

- .github/workflows/release.yml
This PR updates the logic of the `release-unified` job.  Specifically setting the correct branch variable and using it in other steps of the job.
> Update logic of release-unified job

- .github/workflows/build-unified.yml
Forgot a missing `$` for a bash variable.
> Build Unified Workflow - Missing '$'

- .github/workflows/build-unified.yml
- Unified build fails when build is triggered by PR
> FIX: unified selfhost

- .github/workflows/release.yml
Publish `beta` tag alongside versioned `beta` tag to docker hub.
> [DEVOPS-1576] Fix the Unified beta tag

- .github/workflows/DCT-test.yml
> [DEVOPS-1566] - add DCT test workflow

- .github/workflows/release.yml
- Use skopeo to pull multi-arch image from ACR and push to docker hub
> Devops 1574 unified release did not publish arm

- .github/workflows/release.yml
This PR adds the proper login step for Azure CLI before we use Skopeo to login to the ACR.
> Release workflow - Fix Unified job

- .github/workflows/release.yml
- Fixes [this]( https://github.com/bitwarden/self-host/actions/runs/6726570637/job/18283073135#step:5:20) release failing wf
> fix failed release

- .github/workflows/build-unified.yml
- .github/workflows/update-versions.yml
This PR fixes a minor bug by removing a forward slash.
> Build Unified workflow - Fix small bug

- DigitalOceanMarketplace/scripts/99-img-check.sh
This PR updates the Digital Ocean img-check script to the latest version.
> Update Digital Ocean image check script

- .github/workflows/DCT-test.yml
- .github/workflows/build-unified.yml
- .github/workflows/release-digital-ocean.yml
- .github/workflows/release-web-latest.yml
- .github/workflows/update-links.yml
- .github/workflows/update-versions.yml
This PR pins all the `gh-actions` hashes to `master`.
> Pin all gh-actions hashes to master

- .github/workflows/DCT-test.yml
- .github/workflows/build-unified.yml
- .github/workflows/release-digital-ocean.yml
- .github/workflows/release-web-latest.yml
- .github/workflows/release.yml
- .github/workflows/update-links.yml
- .github/workflows/update-versions.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

- .github/workflows/build-unified.yml
- docker-unified/Dockerfile
- Update commands to grab the latest web tag.
- Fix a typo
> [DEVOPS-1648] - Update commands to grab the latest web tag

- .github/workflows/build-unified.yml
- .github/workflows/release.yml
- .github/workflows/update-versions.yml
```
```
Update workflows to point to `main`
- **.github/workflows/*:** Change all relevant references of internal `master` branches to `main`
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)
> Point workflows to `main`

- .github/workflows/build-unified.yml
- docker-unified/Dockerfile
This PR updates the Unified Dockerfile so that it always grabs the latest HBS artifact.
> DEVOPS-1805 - Update to latest HBS artifact

- .github/workflows/build-unified.yml
- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1803)
> [DEVOPS-1803] - Update Failure Job

- .github/workflows/build-unified.yml
[Card](https://bitwarden.atlassian.net/browse/DEVOPS-1803)
> [DEVOPS-1803] - Fix jobs failure check

- .github/workflows/release.yml
https://bitwarden.atlassian.net/browse/BRE-127
> [BRE-127] Remove version input in self host release

- .github/workflows/update-versions.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-246)
- Use GH app as auto PR creator
> [BRE-246] - Use GH-App for version bump workflow

- .github/workflows/DCT-test.yml
- .github/workflows/build-unified.yml
- .github/workflows/release-digital-ocean.yml
- .github/workflows/release-web-latest.yml
- .github/workflows/release.yml
- .github/workflows/update-links.yml
- .github/workflows/update-versions.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-372)
> [BRE-372] - Clean up document start

- docker-unified/hbs/nginx-config.hbs
SRE-1337
Re: PM-846
Added SimpleLogin to CSP
- 🎨 …
> [SRE-1337] fix: SimpleLogin added to CSP per PM-846

- .github/workflows/release.yml
https://bitwarden.atlassian.net/browse/BRE-130
Automate release notes with correct web and core versions.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …
> BRE-130 Release Notes for self-host are automatically generate by GitHub Workflow

- .github/workflows/release.yml
- Fix extra `v` in the `$_LATEST_SELF_HOST_VERSION` variable in Release workflow
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …
> fix version typo

- .github/workflows/release.yml
- Fix checkout
- 🎨 (`:art:`) for suggestions / …
> fix checkout

- .github/workflows/build-unified.yml
https://bitwarden.atlassian.net/browse/BRE-499
- Unified build trigger needs the `is_workflow_call` input, even though the GH API trigger from server is a Workflow Dispatch
- 🤔 (`:thinking:`) or 💭 …
> Update SH Unified Build trigger

- .github/workflows/build-unified.yml
https://bitwarden.atlassian.net/browse/BRE-500
- 🎨 …
> [BRE-500] Update SH Unified Builds to use trigger check

- .github/workflows/release.yml
Due to fully automated GitHub release creation, `update-links` and `release-digital-ocean` workflows are not triggered (due to GitHub Release being published by a github bot). This PR adds a trigger for those workflows after a successful release.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or …
> Trigger update-links and release-digital-ocean workflows on release

- .github/workflows/release.yml
https://bitwarden.atlassian.net/browse/BRE-508
- 🎨 …
> [BRE-508] Fix automated self-host release notes

- .github/workflows/release.yml
[BRE-550](https://bitwarden.atlassian.net/browse/BRE-550) 
Handling multiline release notes when creating Github release
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
> [BRE-550] Handling multiline release notes

- .github/workflows/build-unified.yml
- .github/workflows/release.yml
- .github/workflows/update-versions.yml
- README.md
- [BRE-648](https://bitwarden.atlassian.net/browse/BRE-648?atlOrigin=eyJpIjoiYTQ2NTgxMTRlY2UxNDVhM2E1YjM4OTlhZGE2MGY0YTEiLCJwIjoiaiJ9)
- Added additional logic to the `build-unified` and `release` workflows for pushing images to `ghcr.io`.
- The `README` has been updated.
- Other miscellaneous fixes/updates. …
> BRE-648 - Add logic to push images to ghcr.io

- .github/workflows/release.yml
[BRE-648](https://bitwarden.atlassian.net/browse/BRE-648)
Installing cosign
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …
> Bre 648 fixing unified release

- .github/workflows/build-unified.yml
- .github/workflows/release-digital-ocean.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/update-versions.yml
- DigitalOceanMarketplace/files/var/lib/cloud/scripts/per-instance/001_onboot
- bitwarden.ps1
- bitwarden.sh
- docker-unified/docker-compose.yml
- run.ps1
- run.sh
- [BRE-648](https://bitwarden.atlassian.net/browse/BRE-648?atlOrigin=eyJpIjoiMmEyOGI0OGFhMWRjNGJkMmFhMjZiMDIyYWZiZWNjNjgiLCJwIjoiaiJ9)
This PR updates all references from DockerHub to ghcr.io.
- 🤔 …
> BRE-648 - Change image location from DockerHub to ghcr.io

- .github/workflows/release.yml
- .github/workflows/update-versions.yml
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) …
> Reduce token scope, install cosign for release, minor fixes

- .github/workflows/build-unified.yml
- .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-226
Add correct ref/sha reference for main and PR branches, since codeql/upload-sarif doesn't handle pull_request_target properly.
- 🤔 (`:thinking:`) or 💭 …
> Fix SARIF upload branch ref/sha

- .github/workflows/release.yml
This PR changes to using `skopeo` for copying our images from the ACR to GHCR. This will enable us to easily copy multi-arch images when they are available for the Server and Web projects.
- 🤔 …
> Change to skopeo for copying multi-arch images

- .github/CODEOWNERS
[BRE-457](https://bitwarden.atlassian.net/browse/BRE-457)
Update CODEOWNERS according to the following points on the [Self-Host Ownership Plan](https://bitwarden.atlassian.net/wiki/spaces/BRE/pages/1333362690/Self-host+ownership+and+2025+Q1+plan#Self-host-ownership)
- BRE should own the [self-host repository, which includes install scripts and pipelines.](https://bitwarden.atlassian.net/wiki/spaces/BRE/pages/1333362690/Self-host+ownership+and+2025+Q1+plan#Self-Host-Repository)
- Platform Team should own the [Bitwarden (docker) unified](https://bitwarden.atlassian.net/wiki/spaces/BRE/pages/1333362690/Self-host+ownership+and+2025+Q1+plan#Bitwarden-unified).
- Written new unit and / or integration tests …
> [BRE-457] Updating CODEOWNERS for self-host ownership

- .github/workflows/build-unified.yml
https://bitwarden.atlassian.net/browse/BRE-461
Add option to use latest core version in build unified workflow, to build with latest released server and web.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
> [BRE-461] Implement new self-host docker unified release process

- .github/workflows/build-unified.yml
- .github/workflows/release-digital-ocean.yml
- .github/workflows/release.yml
This PR updates some of the workflows that are missing the top-level permissions block. This satisfies the workflow linter so that we can merge some other PRs.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
> Add top-level permissions block to satisfy workflow linter

- docker-unified/docker-compose.yml
Brings the example up-to-date and consistent whith what we use for self-host. 
https://github.com/bitwarden/server/blob/main/util/MsSql/Dockerfile#L1
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
> Update MSSQL example to mssql server 2022

- .github/workflows/build-unified.yml
- .github/workflows/release-digital-ocean.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
- .github/workflows/update-versions.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Updating to use Azure Key Vault Secrets in place of GitHub secrets.
All GitHub secrets have been migrated to the repository's respective Key Vault.
Azure Service Principals have been updated to use Managed Identities with OIDC.
- 📝 (`:memo:`) or ℹ️ …
> [BRE-831] migrate secrets AKV

- .github/workflows/build-unified.yml
- docker-unified/Dockerfile
- docker-unified/entrypoint.sh
[BRE-924](https://bitwarden.atlassian.net/browse/BRE-924)
relevant PRs in Server and Clients part of the same body of work
- https://github.com/bitwarden/clients/pull/15270
- https://github.com/bitwarden/server/pull/5976
update unified dockerfiles to use alpine as the base image. update package manager commands and entrypoint script to be compatible …
> BRE-924/update-unified-to-alpine
