bitwarden/self-host

.github/workflows/update-links.yml

This PR adds the workflow_dispatch type to the Update Links workflow.  This will allow running manually if needed.

Add workflow_dispatch type to Update Links workflow

---

.github/workflows/update-links.yml

This PR fixes problems with the link variables.  The links were not generated properly, but now should use the tag name from the publish event or from the input if run manually.

Patch Update Links workflow

---

.github/workflows/release.yml
.github/workflows/update-links.yml
.github/workflows/update-versions.yml
bitwarden.ps1
bitwarden.sh
version.json

- Adds version.json with core, web, and KC versions
- Updated Bitwarden scripts to query VERSION_ENDPOINT
- VERSION_ENDPOINT is set to Rebrandly link, redirecting to version.json
- Workflows updated to handle new link, version.json, and version bumps.
---
For testing:
1. Update Rebrandly link to point to this raw file https://raw.githubusercontent.com/bitwarden/self-host/e31909dddb68a6ce16fe9ea8906f6d018ec05fa8/version.json
2. On a new line before line number 61, place a `return`. https://github.com/bitwarden/self-host/pull/17/files#diff-e09e1b8249873e4d6c69fad97e494a37f9380c7894e347072d8735f920a4c555L61
3. Run the `bitwarden.sh install` command.

Add version.json

---

.github/workflows/release.yml
.github/workflows/update-links.yml
.github/workflows/update-versions.yml
bitwarden.ps1
bitwarden.sh
version.json

Reverts most of the changes in PR 17.
- Keeps `version.json`
- Updates workflows to bump version in `version.json` and add it to our release assets.

Revert changes in PR-17

---

.github/workflows/release-digital-ocean.yml

This will allow the `Digital Ocean Image Cleanup` step to run only if the workflow run was NOT triggered on `release` and `workflow_dispatch`.

Change the 'Digital Ocean Image Cleanup' logic

---

.github/workflows/release.yml

Move the `latest` tag to be created on update to the self-host script instead of the server/web releases.
Related PRs:
- https://github.com/bitwarden/clients/pull/3044
- https://github.com/bitwarden/server/pull/2098

[DEVOPS-832] Update timing on SelfHost "latest" tag

---

run.sh

modified the grep command after testing on my DevOps provided self host to verify that it can successfully check if the key connector value in bwdata/config.yml is set to true or not

EC-334-update-run.sh-grep-command

---

.github/workflows/release-digital-ocean.yml
.github/workflows/release.yml
.github/workflows/update-links.yml

The GitHub action Azure Key Vault is being deprecated and will no longer be maintained. The outcome of the related spike offers a solution to implement as a drop-in replacement using bash and the Az CLI. All references for the `Azure/get-keyvault-secrets` action will need to be replaced with this bash step in all our workflows.

Update deprecated Azure Key Vault in workflows

---

bitwarden.sh

I encountered tthis issue when `bitwarden.sh` got a `429 Too many requests` response from azure but still stored the erroneous output in `run.sh` and tried to execute it.
```
run.sh: line 1: `System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).'
run.sh: line 1: syntax error near unexpected token `('
```
Complete response it got from Azure:
```
$ cat bwdata/scripts/run.sh
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
at Proxies.Downloads.GetDownloadResponseAsync(String repository, String …
```

Add check for run file download failure

---

.github/workflows/release.yml

Fixed a small typo that is causing the `release` workflow to fail.

Add missing period to jq commands

---

.github/workflows/build-unified.yml
.github/workflows/release.yml

Update bitwarden unified release flow.
For now it tags the image from `rc` or `hotfix-rc` branches as `[version]-beta` e.g.: `2023.5.0-beta`. There are `TODO:` comments in places where values needs to be changed or lines to be uncommented before GA.

[DEVOPS-1203] Update Release Flow

---

.github/workflows/build-unified.yml

GitHub does not checkout the workflow's repository if it is called.  In this case, the checkout step was cloning the `server` repository when it was called instead of the `self-host` repository.  This led to the `docker-unified` folder being missing.

Fix checkout repo step in Build Unified workflow

---

.github/workflows/build-unified.yml

This PR adds some additional logic to the `Build Unified` workflow to detect whether or not the workflow was manually ran, or called by another workflow (`Server Build`).  It also adds back in the protection where we only publish to Docker Hub when both the `server` branch and the branch of this workflow are publish branches (`master`, `rc`, or `hotfix-rc`).

DEVOPS-1446 - Fix logic in Build Unified workflow

---

.github/workflows/build-unified.yml

This PR fixes the checkout step for `workflow_dispatch` from triggering when called using `workflow_call`.  Removed the `required` keys for inputs as they are not needed when specifying the `default` key.

DEVOPS-1446 - Fix if logic for checkout step in Build Unified workflow

---

.github/workflows/build-unified.yml
.github/workflows/release.yml

When the `build-unified.yml` workflow was called from the `server` repository on the `rc` branch, it was setting the `IMAGE_TAG` as `rc`.  This led to the `Generate tag list` step never generating a tag for Docker Hub.  I added the `elif` statement to the `Generate Docker image tag` step to fix this issue by setting the tag to `beta`.
Inside of the `release-unified` job, it was trying to pull `bitwarden/self-host:rc` which has never existed on Docker Hub.  We need to pull the `beta` tag and release that as `bitwarden/self-host:v202X.X.X-beta`. Changing all of the pull and tag steps to use the `beta` tag fixes this issue.
In the future, when we release Unified to GA we will need to update both workflows to use our standard release/tagging processes at that time.

Fix build and release logic for Unified

---

.github/workflows/build-unified.yml
.github/workflows/release-digital-ocean.yml
.github/workflows/release.yml

Get rid of `node12` warnings in GitHub Actions

DEVOPS-1409 Refactor workflows using Azure/login GHA to use v1.4.7 (node16)

---

.github/workflows/build-unified.yml
.github/workflows/release-web-latest.yml
.github/workflows/release.yml

Get rid of The `set-output` command is deprecated warning by updating the version of `bitwarden/gh-actions/setup-docker-trust` GHA.
Related PR: https://github.com/bitwarden/gh-actions/pull/187

DEVOPS-1408 Refactor Release workflow to use updated version of bitwarden/gh-actions/setup-docker-trust

---

.github/workflows/build-unified.yml
.github/workflows/release.yml

- After the Server build workflow had stop pushing to DockerHub, we need the to update the Self-host release to pull from Prod ACR and tag and push to DockerHub for public consumption.
- **.github/workflows/build-unified.yml**: Self-host build pushes to DH and Prod ACR
- **.github/workflows/release.yml**: Self-host release is pulls latest tag from Prod ACR.
- **.github/workflows/release.yml**: Self-host release is pushing latest and 202X.X.X to DockerHub.

[DEVOPS-1518] UPDATE: initial changes for ACR related work on all workflows

---

docker-unified/hbs/nginx-config.hbs

- Repeat proxy pass through for the anonymous-hub that enables Login with device
I believe this would fix bitwarden/server#3103, described in the PR, they are able to request it, receive it on their phone, confirm that request but their original client never gets told it completed. This would lend to 2 possible errors, their confirming client is never actually telling the server that it was confirmed or the server is not able to notify the originating client of the success. The following log makes me think the originating client isn't actually able to connect to the anonymous-hub (or even see it). Going by this config we have special rules for the existing `hub` but not this new one.
```
Error: WebSocket failed to connect. The connection could not be found on the server, either the …
```

[PM-3019] Add Proxy Passthrough

---

.github/workflows/release.yml

- Include the Migrator Utility as part of the BW stack getting pushed to Docker Hub.

[DEVOPS-1566] - ADD: Migrator utility to DH

---

.github/workflows/release.yml

This is part of our effort to move the s3 buckets that are in Dev/Test to the Prod AWS accounts. This PR removes the bucket name for Self-Host and replaces it with a secret to match the setup for the client's workflow. Our main goal for this is to move production data to production accounts. 
With this change, the new bucket name is now held in the key vault in Azure, with a secret named aws-selfhost-version-bucket-name, which contains the new bucket name for the self-host version artifacts. 
This will also allow us to not have to make code changes if bucket names do change; we will just be able to change the secret. 
Let me know if there are any questions. Or any other places that will have to be updated along with this. Since the client's workflows use a secret in the key vault, once …

Changing the  self-host workflow s3 bucket name to use a secret and not use the bucket name. 

---

.github/workflows/release.yml

- This [card](https://bitwarden.atlassian.net/browse/DEVOPS-1645)
- Fixes the missing beta tag that's missing when we release

[DEVOPS-1645] - FIX: beta tag for docker hub

---

bitwarden.sh

Running the install script as root causes known issues in the product. The person running the script may not realise that a dedicated user is advised in the documentation or have missed the step to create the Bitwarden user. This will also catch users who are running an update of the product as the root user, which can also cause issues. 
It is worth noting that this may result in an increase of service desk tickets for users upgrading who have historically done so as root and are now concerned.

Added a warning message if running the Bitwarden Install script as root

---

bitwarden.sh

Introduces a new feature to the Bitwarden self-hosted script `bitwarden.sh` – the ability to compress and archive logs within a specified date range, or all logs if no range is provided. 
This enhancement simplifies log management, particularly for troubleshooting and audit purposes, by allowing administrators to easily package relevant log files.
Compress logs from March 4th, 2024 to March 5th, 2024:
```bash
./bitwarden.sh compresslogs 20240304 20240305
```
A compressed file `bitwarden-logs-20240304-to-20240305.tar.gz` is produced.
Compress all logs:
```bash
./bitwarden.sh compresslogs
```
A compress file `bitwarden-logs-all.tar.gz` is produced
Please review this PR for inclusion in the next release of Bitwarden self-hosted. Your feedback and suggestions are welcome!

Add compressLogs Functionality to Bitwarden Self-Hosted (Bash)

---

.github/workflows/update-versions.yml

This PR updates the `update-versions` workflow to use the Bitwarden DevOps Bot user to create the PR.  This fixes issues with running the required checks.

DEVOPS-1904 - Update update-version workflow

---

.github/workflows/update-versions.yml

This PR fixes the order of the steps in the `Update Versions` workflow so that the `Import GPG` action can work properly.

DEVOPS-1904 - Fix order of steps

---

.github/workflows/release.yml

- Remove R2 bucket secrets and publish artifacts to R2 step from selfhost release workflow
- This is required as part of the migration from Cloudflare to Fastly for this static asset
- We will use the existing AWS S3 buckets as the origins fronted by Fastly
- **release.yml** Removed R2, CF secrets from **Retrieve secrets** step and removed **Publish artifacts to R2** step

CLOUDOPS-1486 Remove R2 secrets and step from selfhost

---

docker-unified/docker-compose.yml

Version is completely optional for docker compose and in the newest version is being labeled as obsolete. 
[04-version-and-name.md](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md)

Remove version in docker-compose

---

docker-unified/Dockerfile

- [Card](https://bitwarden.atlassian.net/browse/BRE-241?atlOrigin=eyJpIjoiMzY0YzIzOTgzMTI1NDUyYWFlNmM3OGEwNGY5NTJlYTEiLCJwIjoiaiJ9)
This PR removes `gulp` from the `Dockerfile` for Bitwarden Unified as it's no longer used.
- [Successful Test Run](https://github.com/bitwarden/self-host/actions/runs/10354850956)

BRE-241 - Fix Docker Unified Builds

---

bitwarden.sh

This fixes #262 by only overwriting an existing `run.sh` script if we receive a success response.

[PM-8825] Fix: `run.sh` script is deleted if bad response code is received

---

run.ps1
run.sh

This fixes an issue where the run script was attaching itself to an isolated container network, even when using an external database, causing database updates to fail.
To fix this, we simply omit the `--network container:$MSSQL_ID` arg to docker when running the DB update when using an external database.

[PM-368] Setup container attaches itself to docker_internal network during database update

---

bitwarden.sh
run.ps1
run.sh

Resolves #222. Removes compatibility with the deprecated `docker-compose` Python CLI. Users will need to upgrade to a modern, [supported version of Docker](https://bitwarden.com/help/install-on-premise-linux/#system-specifications) to continue self-hosting Bitwarden with our standard deployment process.
Note that this is only applicable to the Linux script. `docker-compose` on Windows is **not** the same thing as the deprecated `docker-compose` CLI.

Breaking change: remove support for deprecated `docker-compose` CLI

---

.github/workflows/build-unified.yml

https://bitwarden.atlassian.net/browse/VULN-130
Signs Unified container images built off `main` with [Cosign](https://github.com/sigstore/cosign). This uses Sigstore's in-house certificate authority with short-lived keys that are all self-managed with the tool, which will also utilize GitHub's provided OIDC entity. As part of an effort to increase transparency of what we build as an open source company, these signatures are also sent to [Rekor](https://search.sigstore.dev/) -- users of our images are then free to verify the images against that log.
Also throws in container security scanning as that's adjacent in other builds.
- Protected …

Sign main branch Unified container builds with cosign and perform security scanning

---

.github/workflows/build-unified.yml

Follow-up to https://github.com/bitwarden/self-host/pull/325.
We want the Cosign work to occur only for published branches.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …

Run cosign only for published branches

---

.github/workflows/release.yml

[BRE-648](https://bitwarden.atlassian.net/browse/BRE-648)
Fixing `_RELEASE_TAG` variable in release unified section to be `_RELEASE_VERSION`
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

[BRE-648] Fixing released unified to use correct variable

---

docker-unified/Dockerfile

Sonarcloud security hotspot: `curl` with `-L` without `--proto "=https"` can lead to plain-text downgrade i.e. it can be redirected to an `http` url
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …

fix: curl clear-text protocol downgrade risk

---

docker-unified/hbs/nginx-config.hbs

Uncomment the listen directive for IPv6.
Fixes #172.
Have nginx listen on both IPv4 and IPv6. IPv6 listen directive is commented out for seemingly no reason.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …

Listen on IPv4 and IPv6
